
import type { Metadata } from "next";
import {Montserrat} from 'next/font/google'
import "../global.scss";
import {AosProvider} from '../../providers/AosProvider'
import { CartProvider } from "@/lib/cart.context";
import { Toaster } from 'sonner'
const monserrat = Montserrat({
  subsets: ['cyrillic'],
  preload: true,
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: "Destiny Hardware",
  description: "Generated by create next app",
};

export default function HomePage({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    
    <html lang="en">
      <body
      className={monserrat.className}
      >
        <CartProvider>
        <AosProvider>
        <Toaster richColors/>
        {children}
          </AosProvider>
        </CartProvider>
      </body>
    </html>
  );
}
