/* ------------------------------Imports---------------------------- */
//Styles
import "../global.scss";
//Components
import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import Navigation from "@/components/dashboard/Navigation";
import { Toaster } from 'sonner'
//Icons
//Props
//React
import React from "react";
import {AosProvider} from "../../providers/AosProvider";
import {AuthProvider} from "../../providers/AuthProvider";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth/next";
import { redirect } from "next/navigation";
//Images
/*---------------------------------------------------------------------- */
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const monserrat = Montserrat({
  subsets: ["cyrillic"],
});

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = async ({ children }) => {
  const session = await getServerSession(authOptions);
  if (!session || !session.user?.email) {
    redirect("/login");
  } else {
    return (
      <html lang="en">
        <body className={monserrat.className}>
          <main style={{ width: "100%", height: "100%" }}>
            <Navigation />
            <AosProvider>
              <Toaster richColors/>
              <AuthProvider>{children}</AuthProvider>
            </AosProvider>
          </main>
        </body>
      </html>
    );
  }
};

export default Layout;
